export const SITE = {
  website: "https://hez2z.github.io/astro-exam-code/",
  author: "HeZzz",
  profile: "https://github.com/HeZ2z",
  desc: "汇总课程回忆版、期末重点、小测整理与复习资料。",
  title: "期末复习资料站",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 10,
  postPerPage: 10,
  scheduledPostMargin: 0,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "编辑此页",
    url: "https://github.com/HeZ2z/astro-exam-code/edit/main/",
  },
  dynamicOgImage: true,
  dir: "auto",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
